---
# vim: ts=2:sw=2:sts=2:et:ft=yaml.ansible
#
# Configure group_vars/group.yml files
#
########################################################################

# Create a group_vars file for each group, excluding the ungrouped group
# or any group beginning with an underscore.
- name: Template group variables files if they doesn't exist
  ansible.builtin.template:
    src: group_vars.yml.j2
    dest: "{{ gv_file_var}}"
    mode: 0644
    force: false
    backup: "{{ inv_bu }}"
  vars:
    gv_file_var: "{{ inventory_dir }}/group_vars/{{ group_item }}.yml"
    title_var: "Group Variables - {{ group_item }}"
    header_var: "\
      {{  ( title_var + '\n \n' + default_comment_header )
          | wordwrap(70)
          | comment(  prefix=yaml_comment_prefix,
                      postfix=default_comment_postfix ) }}"
  loop: "{{ groups.keys()
            | list
            | reject('==', 'ungrouped')
            | reject('match', '^_.*$')
            | union( new_groups | default([]) ) }}"
  loop_control:
    loop_var: group_item
  notify: git commit inventory
