---
# vim: ts=2:sw=2:sts=2:et:ft=yaml.ansible
#
# Configure the group_vars/all.yml file
#
########################################################################

# Use existing values in present
- name: "Load variables from {{ all_gv_file_var }}"
  ansible.builtin.include_vars: "{{ all_gv_file_var }}"

# Defined in defaults/main.yml
- name: "Write comment defaults to {{ all_gv_file_var }}"
  ansible.builtin.blockinfile:
    path: "{{ all_gv_file_var }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: Comment Defaults (Editable)"
    block: "{{  yaml_wrapper_var
                | to_nice_yaml(width=1023, indent=2) }}"
    insertbefore: "{{ safe_zone_comment }}"
    mode: 0644
    backup: "{{ inv_bu }}"
  vars:
    yaml_wrapper_var:
      default_comment_prefix: "{{ default_comment_prefix }}"
      ansible_comment_prefix: "{{ ansible_comment_prefix }}"
      yaml_comment_prefix: "{{ yaml_comment_prefix }}"
      default_comment_postfix: "{{ default_comment_postfix}}"
      safe_zone_comment: "{{ safe_zone_comment }}"
  notify: git commit inventory

# Defined in defaults/main.yml
- name: "Write software defaults to {{ all_gv_file_var }}"
  ansible.builtin.blockinfile:
    path: "{{ all_gv_file_var }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: Software Defaults (Editable)"
    block: |
      {{ yaml_wrapper_var | to_nice_yaml(width=1023, indent=2) }}
    insertbefore: "{{ safe_zone_comment }}"
    mode: 0644
    backup: "{{ inv_bu }}"
  vars:
    yaml_wrapper_var:
      arch_defaults: "{{ arch_defaults }}"
      release_defaults: "{{ release_defaults }}"
  notify: git commit inventory
