---
# vim: ts=2:sw=2:sts=2:et:ft=yaml.ansible
#
# Configure the host_vars/host.yml file
#
########################################################################

- name: Template host variables file if it doesn't exist
  ansible.builtin.template:
    src: host_vars.yml.j2
    dest: "{{ hv_file_var}}"
    mode: 0644
    force: false
    backup: "{{ inv_bu }}"
  vars:
    hv_file_var: "{{ inventory_dir }}/host_vars/{{ inventory_hostname }}.yml"
    title_var: "Host Variables - {{ inventory_hostname }}"
    header_var: "\
      {{  ( title_var + '\n \n' + default_comment_header )
          | wordwrap(70)
          | comment(  prefix=yaml_comment_prefix,
                      postfix=default_comment_postfix ) }}"
  notify: git commit inventory
