---
# vim: ts=2:sw=2:sts=2:et:ft=yaml.ansible
#
# Define the byline and comment header based on collection or role
# metadata.
#
########################################################################

- name: Define the byline
  ansible.builtin.set_fact:
    byline: "{{ ( ansible_collection_meta is defined )
                | ternary(collect_line_var, role_line_var) }}"
  vars:
    collect_fqcn_var: "{{ [ ansible_collection_meta['namespace'],
                            ansible_collection_meta['name'] ]
                          | join('.') }}"
    collect_vers_var: "{{ ansible_collection_meta['version'] }}"
    collect_line_var: >-
      {{ collect_fqcn_var}} collection (version {{ collect_vers_var }})
    role_line_var: >-
      {{  ansible_parent_role_names
          | default( [ansible_role_name] )
          | first }} role

# The comment header is used for templates to indicate what collection
# or role was used.
- name: Define the default comment header
  ansible.builtin.set_fact:
    default_comment_header: "Generated by the {{ byline }}."
