---
# vim: ts=2:sw=2:sts=2:et:ft=yaml.ansible
#
# Inventory handlers
#
########################################################################

- name: git commit inventory
  ansible.builtin.include_tasks: cfg_git.yml
  when: inv_git == true
